export const SET_USER_PENDING = 'SET_USER_PENDING';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const GET_USER = 'GET_USER';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const CURRENT_MSGING = 'CURRENT_MSGING'
// export const SET_USER_FAILURE = 'SET_USER_FAILURE'